{
 "title": "Wind Turbines Monitoring",
 "time": { "from": "2023-10-25T19:28:51.897Z", "to": "2023-10-25T19:30:42.309Z" },
 "panels": [
  {
   "title": "Summary KPIs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n  count(distinct d.deviceId) as `# Turbines`,\n  count(distinct d.field_name) as `# Fields`,\n  count(distinct d.model_name) as `# Models`,\n  sum(t.power) as `Produced Power`,\n  avg(t.temperature) as `Avg. Temperature`,\n  avg(t.humidity) as `Avg. Humidity`,\n  avg(t.windspeed) as `Avg. Windspeed`,\n  max(t.age) as `Max. Age`\n  --,count(distinct case when t.remaining_life < 7 then t.deviceid end) as `Alerts`\nfrom vr_iiot.dev.devices d\nleft join vr_iiot.dev.turbine_enriched t\non t.deviceid = d.deviceId\nwhere $__timeFilter(t.window)"
    }
   ]
  },
  { "title": "Turbine Status Map", "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 } },
  {
   "title": "Produced Power by Turbine",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "rawSql": "select\n  cast(t.deviceId as string) as `Turbine`,\n  avg(t.power) as `Produced Power`\nfrom vr_iiot.dev.turbine_raw t\nwhere $__timeFilter(timestamp)\ngroup by t.deviceid"
    }
   ]
  },
  {
   "title": "Turbine Detail",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "rawSql": "select\n  d.deviceId as `Turbine`,\n  case when avg(t.remaining_life) < 7 then 'ALERT'\n       else 'OK'\n       end as `Status`,\n  avg(t.remaining_life) as `Remaining Life`,\n  d.model_name as `Model Name`,\n  d.field_name as `Field Name`,\n  avg(t.rpm) as RPM,\n  avg(t.angle) as Angle,\n  avg(t.power) as Power,\n  avg(t.temperature) as Temperature,\n  avg(t.humidity) as Humidity,\n  avg(t.windspeed) as Windspeed,\n  max(t.age) as Age\nfrom vr_iiot.dev.devices d\nleft join vr_iiot.dev.turbine_enriched t\non t.deviceid = d.deviceId\nwhere $__timeFilter(t.window)\ngroup by d.deviceid, d.model_name, d.field_name, d.lat, d.lon\norder by `Remaining Life`, `Turbine`"
    }
   ]
  },
  {
   "title": "Produced Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select\n  window.start as window,\n  deviceId,\n\tsum(power) as power\nfrom vr_iiot.dev.turbine_raw\nwhere $__timeFilter(timestamp)\ngroup by window(timestamp, '$__interval_long'), deviceId"
    }
   ]
  }
 ]
}